INSERT INTO CUSTOMER (ID, NAME, LAST_NAME, IDENTIFICATION) VALUES (NULL, 'Joel', 'Vargas Lindarte','123123123');
INSERT INTO CUSTOMER (ID, NAME, LAST_NAME, IDENTIFICATION) VALUES (NULL, 'Alejandro', 'Lindarte Castro','1232123123');
INSERT INTO CUSTOMER (ID, NAME, LAST_NAME, IDENTIFICATION) VALUES (NULL, 'Freddy', 'Vargas Lindarte','1231233123');
INSERT INTO CUSTOMER (ID, NAME, LAST_NAME, IDENTIFICATION) VALUES (NULL, 'Carlos', 'Lindarte','1231234123');

COMMIT;